# Site settings
title: Morey Tech Limited
email: info@morey.tech
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://morey.tech" # the base hostname & protocol for your site

twitter_username: morey_tech
github_username: morey-tech
linkedin_username: nicholas-morey

# Build settings
markdown: kramdown
